Repository ISISComputingGroup/ProjectBoardUtils, pull requests merged in 2021-01, with the labels that each got.

#1 Ticket 2185: Added checks for release notes
  README.md
  card.py
  release_notes_checker.py
  requirements.txt
  tests/test_utils.py
  utils.py
Labels: size/L

#2 Add wontfix
  card.py
Labels: size/XS

#3 Run release notes checker too
  card_day.sh
Labels: size/XS

#4 Make sure column values of enums are used not the enum when comparing…
  card.py
  utils.py
Labels: size/M

#5 Ignore support tickets and print a url
  release_notes_checker.py
Labels: size/XS
